notifications:
  email: false

sudo: required

services:
  - docker

language: python
python: 2.7

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

install:
  - pip install fabric

script:
  - cp env.example .env
  - docker-compose build
  - docker-compose up -d postgres
  - docker-compose run --rm api python manage.py migrate
  - docker-compose run --rm api python manage.py collectstatic
  - docker-compose run --rm -e TEST=true api py.test
