version: '3'

services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:11
    volumes:
      - ~/data/leviatan/postgres:/var/lib/postgresql/data
    env_file: ./.env

  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./api:/srv/www/api
      - ./public:/srv/www/public
    command: celery -A api beat -l info --pidfile="/srv/www/celerybeat.pid"
    depends_on:
      - redis
      - postgres

  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./api:/srv/www/api
      - ./public:/srv/www/public
    command: celery -A api worker -l info --pidfile="/srv/www/celeryworker.pid"
    depends_on:
      - redis
      - postgres

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./api:/srv/www/api
      - ./public:/srv/www/public
    command: celery flower -A api --port=5555 --basic_auth=dev:dev123 --pidfile="/srv/www/flower.pid"
    depends_on:
      - celerybeat
      - celeryworker
    ports:
      - "5555:5555"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./api:/srv/www/api
      - ./public:/srv/www/public
      - ~/data/leviatan/backups:/srv/www/backups
    working_dir: /srv/www/api
    command: python manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - redis
      - postgres
    ports:
      - '8000:8000'
